// src/app/product/[id]/page.tsx
'use client';

import React, { useState, useEffect } from 'react';
import { useParams } from 'next/navigation';
import Link from 'next/link';
import { ArrowLeft, Loader2, CheckCircle2, Box, Send, AlertTriangle, Layers } from 'lucide-react';
import { generate3DModel, publishToStore } from '@/app/actions';
import { Product, getShopifyProducts } from '@/lib/shopify';
import VoxelRenderer from '@/components/VoxelRenderer';

// Type from lib/openai
interface PrimitiveData {
    type: 'box' | 'sphere' | 'cylinder';
    position: [number, number, number];
    rotation: [number, number, number];
    scale: [number, number, number];
    color: string;
}

export default function ProductPage() {
    const params = useParams();
    const [product, setProduct] = useState<Product | null>(null);
    const [email, setEmail] = useState('demo@example.com');
    const [status, setStatus] = useState<'idle' | 'generating' | 'complete' | 'failed'>('idle');
    const [voxelData, setVoxelData] = useState<PrimitiveData[] | null>(null);
    const [mockModelUrl, setMockModelUrl] = useState<string | null>(null);

    useEffect(() => {
        getShopifyProducts().then(products => {
            const p = products.find(p => p.id === params.id);
            if (p) setProduct(p);
        });
    }, [params.id]);

    const handleGenerate = async () => {
        if (!product) return;
        setStatus('generating');

        try {
            // mode='real' triggers the OpenAI Voxel flow
            const result = await generate3DModel(product.id, email, 'real');

            if (result.success && result.voxelData) {
                // Real OpenAI Result
                setVoxelData(result.voxelData);
                setStatus('complete');
            } else if (result.success && result.modelUrl) {
                // Mock Fallback
                setMockModelUrl(result.modelUrl);
                setStatus('complete');
            } else {
                setStatus('failed');
            }
        } catch (e) {
            console.error(e);
            setStatus('failed');
        }
    };

    if (!product) return <div className="text-center py-20 text-muted-foreground">Loading Product...</div>;

    const isVoxel = status === 'complete' && voxelData;
    const isMock = status === 'complete' && mockModelUrl;

    return (
        <div className="max-w-5xl mx-auto">
            <Link href="/" className="inline-flex items-center text-sm text-muted-foreground hover:text-foreground mb-8 transition-colors">
                <ArrowLeft className="w-4 h-4 mr-2" /> Back to Dashboard
            </Link>

            <div className="grid grid-cols-1 md:grid-cols-2 gap-12">
                {/* Visual Side */}
                <div className="space-y-6">
                    <div className="aspect-square rounded-2xl bg-secondary/50 border border-white/5 overflow-hidden relative group">
                        {isVoxel ? (
                            <div className="w-full h-full bg-black/40">
                                {/* Use key to force re-mount on new data */}
                                <VoxelRenderer key={JSON.stringify(voxelData)} data={voxelData || []} />
                                <div className="absolute bottom-4 left-0 right-0 text-center pointer-events-none">
                                    <span className="bg-black/50 backdrop-blur px-3 py-1 rounded-full text-xs font-mono text-white">
                                        Generated by OpenAI Vision
                                    </span>
                                </div>
                            </div>
                        ) : isMock ? (
                            <div className="w-full h-full flex items-center justify-center bg-black/20">
                                <div className="text-center space-y-4 animate-in fade-in zoom-in duration-500">
                                    <div className="w-20 h-20 bg-primary/20 rounded-full flex items-center justify-center mx-auto shadow-[0_0_30px_rgba(34,197,94,0.3)]">
                                        <Box className="w-10 h-10 text-primary" />
                                    </div>
                                    <p className="text-primary font-medium">Mock Model Ready</p>
                                </div>
                            </div>
                        ) : status === 'failed' ? (
                            <div className="w-full h-full flex items-center justify-center bg-destructive/10">
                                <div className="text-center space-y-2 text-destructive">
                                    <AlertTriangle className="w-10 h-10 mx-auto" />
                                    <p>Generation Failed</p>
                                </div>
                            </div>
                        ) : (
                            // eslint-disable-next-line @next/next/no-img-element
                            <img
                                src={product.images[0]}
                                alt={product.title}
                                className={`w-full h-full object-cover transition-all duration-700 ${status === 'generating' ? 'scale-110 blur-sm opacity-50' : ''}`}
                            />
                        )}

                        {status === 'generating' && (
                            <div className="absolute inset-0 flex flex-col items-center justify-center z-10 p-6 text-center">
                                <Loader2 className="w-12 h-12 text-primary animate-spin mb-4" />
                                <p className="text-lg font-medium glow-text">Analyzing Geometry...</p>
                                <p className="text-sm text-muted-foreground">GPT-4o Vision Processing</p>
                            </div>
                        )}
                    </div>
                </div>

                {/* Controls Side */}
                <div className="flex flex-col justify-center space-y-8">
                    <div>
                        <div className="flex items-center gap-2 mb-2">
                            <span className="px-2 py-0.5 rounded text-[10px] font-bold bg-green-500/20 text-green-400 border border-green-500/30">OPENAI ENGINE</span>
                            <h2 className="text-primary font-mono text-sm">SKU: {product.id}</h2>
                        </div>
                        <h1 className="text-4xl font-bold mb-4">{product.title}</h1>
                        <p className="text-muted-foreground leading-relaxed text-lg">{product.description}</p>
                    </div>

                    <div className="glass-panel p-6 space-y-6 bg-secondary/10">
                        <div className="flex flex-col gap-2">
                            <label className="text-xs font-semibold uppercase tracking-wider text-muted-foreground">Target Customer Email</label>
                            <input
                                type="email"
                                value={email}
                                onChange={(e) => setEmail(e.target.value)}
                                className="input"
                                placeholder="customer@example.com"
                            />
                        </div>

                        {status === 'complete' ? (
                            <div className="space-y-4">
                                <div className="p-4 bg-primary/10 border border-primary/20 rounded-lg flex items-center gap-3 text-primary">
                                    <CheckCircle2 className="w-5 h-5" />
                                    <span className="font-medium">Voxel Model Generated</span>
                                </div>
                                <div className="grid grid-cols-2 gap-3">
                                    <button className="btn bg-secondary w-full">View Source</button>
                                    <button className="btn btn-primary w-full gap-2">
                                        <Send className="w-4 h-4" /> Publish
                                    </button>
                                </div>
                            </div>
                        ) : (
                            <button
                                onClick={handleGenerate}
                                disabled={status !== 'idle'}
                                className="btn btn-primary w-full text-lg py-4 shadow-[0_0_20px_rgba(34,197,94,0.15)] disabled:opacity-50"
                            >
                                <Layers className="w-5 h-5 mr-2" />
                                {status === 'generating' ? 'Reconstructing...' : 'Generate with OpenAI'}
                            </button>
                        )}

                        <div className="pt-4 border-t border-white/5 text-center">
                            <Link href={`/demo/product/${product.id}`} className="text-xs text-muted-foreground hover:text-primary transition-colors">
                                Switch to Instant Demo Mode (Mock) →
                            </Link>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    );
}
